/**
 * Curated drawable word lists for Scribble (server-only).
 * Words are nouns/concepts that work well on a whiteboard across all ages.
 */

export const EASY_WORDS = [
  'cat', 'dog', 'sun', 'moon', 'tree', 'fish', 'bird', 'car', 'house', 'apple',
  'book', 'ball', 'hat', 'shoe', 'cake', 'rain', 'snow', 'star', 'boat', 'chair',
  'door', 'egg', 'fire', 'gift', 'hand', 'ice', 'juice', 'key', 'lamp', 'milk',
  'nose', 'owl', 'pen', 'queen', 'ring', 'ship', 'toy', 'van', 'water', 'box',
  'cloud', 'drum', 'eye', 'frog', 'grape', 'heart', 'island', 'jump', 'kite',
  'leaf', 'lion', 'map', 'net', 'ocean', 'pizza', 'robot', 'rose', 'sock', 'tea',
  'tiger', 'train', 'truck', 'wave', 'whale', 'window', 'wolf', 'worm', 'bee',
  'bed', 'bell', 'bike', 'bone', 'bow', 'bread', 'brush', 'bus', 'candy', 'cap',
  'clock', 'coin', 'cookie', 'corn', 'cup', 'desk', 'dice', 'duck', 'fan', 'farm',
  'flag', 'flower', 'fork', 'fox', 'game', 'gem', 'ghost', 'girl', 'glass', 'goat',
  'gold', 'grass', 'gun', 'hair', 'hammer', 'hill', 'horse', 'hot', 'jar', 'jet',
  'king', 'kiss', 'knee', 'knife', 'lake', 'leg', 'lemon', 'line', 'lip', 'lock',
  'log', 'love', 'luck', 'mail', 'man', 'mop', 'mouse', 'mud', 'mug', 'neck',
  'nest', 'night', 'nurse', 'nut', 'oar', 'oil', 'olive', 'onion', 'orange', 'palm',
  'pan', 'panda', 'park', 'pear', 'pie', 'pig', 'pill', 'pin', 'pipe', 'pond',
  'pool', 'pop', 'pot', 'pray', 'prize', 'puppy', 'puzzle', 'rabbit', 'radio', 'rake',
  'rat', 'rice', 'road', 'rock', 'room', 'rope', 'rug', 'sad', 'salad', 'sand',
  'santa', 'saw', 'seal', 'seed', 'sheep', 'shell', 'shirt', 'shoe', 'shop', 'shower',
  'sign', 'sing', 'sink', 'skate', 'ski', 'skull', 'sky', 'sled', 'smile', 'snake',
  'snowman', 'soap', 'soda', 'sofa', 'song', 'soup', 'space', 'spoon', 'sport', 'spot',
  'spring', 'spy', 'square', 'squirrel', 'stairs', 'stamp', 'stone', 'stool', 'stop',
  'store', 'storm', 'stove', 'straw', 'street', 'string', 'suit', 'summer', 'swan',
  'swim', 'swing', 'sword', 'table', 'tail', 'tank', 'tap', 'taxi', 'team', 'tent',
  'test', 'thumb', 'tie', 'toast', 'toe', 'tongue', 'tool', 'tooth', 'top', 'tower',
  'town', 'track', 'trail', 'trap', 'tray', 'treat', 'trip', 'trophy', 'tub', 'tube',
  'tulip', 'tuna', 'turtle', 'tv', 'twig', 'type', 'uncle', 'vacuum', 'vase', 'vest',
  'vine', 'violin', 'vote', 'waffle', 'wagon', 'wall', 'wand', 'watch', 'web', 'wedding',
  'well', 'wheel', 'wig', 'wind', 'wine', 'wing', 'wire', 'witch', 'wood', 'wool',
  'world', 'wound', 'wrist', 'yard', 'yarn', 'yawn', 'yellow', 'yoga', 'yolk', 'zero',
  'zipper', 'zoo', 'arch', 'arm', 'art', 'baby', 'back', 'bag', 'bait', 'bake',
  'barn', 'bat', 'beach', 'bean', 'bear', 'beard', 'beet', 'belt', 'bench', 'berry',
  'bib', 'bin', 'birdcage', 'birthday', 'biscuit', 'black', 'blade', 'blanket', 'blimp',
  'block', 'blonde', 'bloom', 'blush', 'board', 'boat', 'body', 'bolt', 'bomb', 'boot',
  'bottle', 'bowl', 'boy', 'brain', 'branch', 'brass', 'brick', 'bridge', 'broom', 'brown',
  'bubble', 'bucket', 'bud', 'bug', 'bulb', 'bull', 'bun', 'bunny', 'burger', 'burn',
  'bus stop', 'bush', 'butter', 'button', 'cabin', 'cable', 'cage', 'camel', 'camp',
  'can', 'candle', 'cane', 'canoe', 'cape', 'card', 'carpet', 'carrot', 'cart', 'case',
  'cash', 'castle', 'catfish', 'cave', 'celery', 'cell', 'chain', 'chair', 'chalk',
  'champ', 'chart', 'cheek', 'cheer', 'cheese', 'cherry', 'chest', 'chicken', 'chin',
  'chip', 'chocolate', 'chop', 'chord', 'church', 'cigar', 'circle', 'circus', 'city',
  'clam', 'clap', 'claw', 'clay', 'cliff', 'climb', 'clip', 'cloak', 'clock', 'closet',
  'cloth', 'clover', 'clown', 'club', 'coach', 'coal', 'coast', 'coat', 'cob', 'cocoa',
  'coconut', 'cod', 'coffee', 'coil', 'cold', 'collar', 'color', 'comb', 'comet',
  'cone', 'cook', 'cool', 'cop', 'coral', 'cork', 'corn', 'cost', 'cot', 'cotton',
  'couch', 'cough', 'count', 'court', 'cousin', 'cover', 'cow', 'crab', 'crack',
  'craft', 'crane', 'crash', 'crawl', 'crayon', 'cream', 'creek', 'crest', 'crew',
  'crib', 'cricket', 'crop', 'cross', 'crow', 'crown', 'cruise', 'crumb', 'crush',
  'cry', 'crystal', 'cube', 'cucumber', 'cuff', 'culture', 'cupcake', 'curb', 'curl',
  'curtain', 'curve', 'cushion', 'cute', 'dad', 'daisy', 'dance', 'dandelion', 'danger',
  'dare', 'dark', 'dart', 'dash', 'data', 'date', 'dawn', 'day', 'dead', 'deal',
  'dear', 'death', 'deck', 'deer', 'defense', 'degree', 'demon', 'dent', 'desert',
  'design', 'desk', 'dew', 'dial', 'diamond', 'diary', 'dice', 'diet', 'dig', 'dill',
  'dime', 'dine', 'dinosaur', 'dip', 'dirt', 'dish', 'dive', 'dock', 'doctor', 'dodge',
  'doghouse', 'doll', 'dolphin', 'domain', 'donkey', 'donut', 'doom', 'doorbell',
  'dough', 'dove', 'down', 'doze', 'draft', 'drag', 'dragonfly', 'drain', 'draw',
  'dream', 'dress', 'drill', 'drink', 'drip', 'drive', 'drool', 'drop', 'drought',
  'drumstick', 'dry', 'dual', 'duckling', 'dude', 'duel', 'duke', 'dull', 'dumb',
  'dune', 'dunk', 'dusk', 'dust', 'duty', 'dwarf', 'dye', 'eagle', 'ear', 'earth',
  'ease', 'east', 'eat', 'echo', 'edge', 'eel', 'effect', 'eggplant', 'elbow',
  'elder', 'electric', 'elf', 'elk', 'elm', 'email', 'ember', 'emu', 'end', 'engine',
  'entry', 'epic', 'era', 'error', 'essay', 'eve', 'even', 'ever', 'evil', 'exam',
  'exit', 'expert', 'extra', 'eyeball', 'eyebrow', 'fabric', 'face', 'fact', 'fade',
  'fair', 'fairy', 'faith', 'fall', 'family', 'fan', 'fang', 'farmer', 'fashion',
  'fast', 'fat', 'father', 'fault', 'fawn', 'fear', 'feast', 'feather', 'feature',
  'fee', 'feed', 'feel', 'feet', 'fence', 'fern', 'ferry', 'festival', 'fever', 'field',
  'fig', 'fight', 'file', 'fill', 'film', 'filter', 'fin', 'final', 'find', 'fine',
  'finger', 'fir', 'firefly', 'fireman', 'fireplace', 'firework', 'first', 'fishbowl',
  'fisher', 'fist', 'fit', 'five', 'fix', 'flagpole', 'flame', 'flamingo', 'flap',
  'flare', 'flash', 'flask', 'flat', 'flavor', 'flea', 'flesh', 'flight', 'flint',
  'flip', 'float', 'flock', 'flood', 'floor', 'flour', 'flow', 'flowerpot', 'flu',
  'flute', 'fly', 'foam', 'fog', 'foil', 'fold', 'folk', 'follow', 'fond', 'food',
  'fool', 'foot', 'football', 'footprint', 'force', 'forest', 'forge', 'forklift',
  'form', 'fort', 'fossil', 'foster', 'foul', 'found', 'fountain', 'four', 'foxhole',
  'frame', 'frank', 'free', 'freeze', 'french', 'fresco', 'fresh', 'fridge', 'friend',
  'frill', 'frogman', 'front', 'frost', 'frown', 'fruit', 'fry', 'fudge', 'fuel',
  'fume', 'fun', 'fund', 'fur', 'furnace', 'furry', 'fury', 'fuse', 'fuss', 'futon',
  'future', 'fuzz', 'gable', 'gadget', 'gag', 'gain', 'galaxy', 'gallery', 'gallon',
  'gallows', 'gamepad', 'gang', 'gap', 'garage', 'garbage', 'garden', 'garlic', 'garnet',
  'gas', 'gasp', 'gate', 'gather', 'gator', 'gauge', 'gavel', 'gaze', 'gear', 'gecko',
  'geese', 'gel', 'gemstone', 'general', 'genie', 'genius', 'genre', 'gentle', 'germ',
  'gesture', 'get', 'geyser', 'giant', 'giftwrap', 'giggle', 'gill', 'gin', 'ginger',
  'giraffe', 'girl', 'give', 'glacier', 'glad', 'glance', 'gland', 'glare', 'glass',
  'glaze', 'gleam', 'glide', 'glider', 'glimmer', 'glimpse', 'globe', 'gloom', 'glory',
  'glove', 'glow', 'glue', 'gnat', 'gnome', 'goal', 'goat', 'goblin', 'goldfish',
  'golf', 'gong', 'goose', 'gopher', 'gorilla', 'gospel', 'gossip', 'gown', 'grab',
  'grace', 'grade', 'grain', 'grandma', 'grandpa', 'grapefruit', 'graph', 'grasp',
  'grasshopper', 'grate', 'grave', 'gravel', 'gravy', 'gray', 'graze', 'grease',
  'green', 'greet', 'grey', 'grid', 'grief', 'grill', 'grin', 'grind', 'grip', 'grit',
  'groan', 'grocery', 'groom', 'groove', 'gross', 'ground', 'group', 'grove', 'grow',
  'growl', 'grub', 'grudge', 'grunt', 'guard', 'guess', 'guest', 'guide', 'guild',
  'guilt', 'guinea', 'guitar', 'gulf', 'gull', 'gum', 'gunpowder', 'guru', 'gush',
  'gust', 'gutter', 'guy', 'gym', 'habit', 'hail', 'haircut', 'hairpin', 'hairy',
  'half', 'hall', 'halo', 'halt', 'ham', 'hamburger', 'hammerhead', 'hammock', 'hamster',
  'handbag', 'handful', 'handle', 'hang', 'hanger', 'happen', 'happy', 'harbor',
  'hard', 'hare', 'harm', 'harp', 'harvest', 'hash', 'haste', 'hatch', 'hate', 'haul',
  'haunt', 'haven', 'hawk', 'hay', 'haze', 'head', 'headband', 'health', 'heap', 'hear',
  'heat', 'hedge', 'hedgehog', 'heel', 'heir', 'helicopter', 'helmet', 'help', 'hem',
  'hen', 'herb', 'herd', 'hero', 'heron', 'hex', 'hibiscus', 'hickory', 'hide', 'high',
  'hike', 'hill', 'hilt', 'hind', 'hinge', 'hint', 'hip', 'hippo', 'hire', 'history',
  'hit', 'hive', 'hobby', 'hockey', 'hoe', 'hog', 'hold', 'hole', 'holiday', 'hollow',
  'holy', 'home', 'honey', 'honk', 'hood', 'hoof', 'hook', 'hoop', 'hoot', 'hop',
  'hope', 'horn', 'hornet', 'horse', 'hose', 'hospital', 'host', 'hotdog', 'hotel',
  'hound', 'hour', 'houseboat', 'hover', 'howl', 'hub', 'hug', 'huge', 'hull', 'hum',
  'human', 'humble', 'hump', 'hunch', 'hungry', 'hunt', 'hurdle', 'hurl', 'hurry',
  'hurt', 'husband', 'hush', 'hut', 'hyena', 'hymn', 'iceberg', 'icing', 'icon', 'idea',
  'ideal', 'idiom', 'idle', 'idol', 'igloo', 'ignite', 'iguana', 'ill', 'image', 'imp',
  'inch', 'index', 'indigo', 'info', 'ink', 'inn', 'input', 'insect', 'inside', 'iron',
  'irony', 'island', 'itch', 'ivory', 'ivy', 'jab', 'jack', 'jacket', 'jackpot', 'jade',
  'jaguar', 'jail', 'jam', 'jar', 'jasmine', 'jaw', 'jazz', 'jeans', 'jelly', 'jellybean',
  'jersey', 'jest', 'jetpack', 'jewel', 'jig', 'jigsaw', 'job', 'jockey', 'jog', 'join',
  'joke', 'jolly', 'jolt', 'journal', 'journey', 'joy', 'judge', 'jug', 'juicebox',
  'jumbo', 'jump', 'jungle', 'junior', 'junk', 'jury', 'just', 'kale', 'kamikaze',
  'kangaroo', 'karaoke', 'karate', 'karma', 'kayak', 'kebab', 'keg', 'kelp', 'kennel',
  'ketchup', 'kettle', 'keychain', 'khaki', 'kick', 'kid', 'kidney', 'kill', 'kilo',
  'kimono', 'kind', 'kingdom', 'kiss', 'kit', 'kitchen', 'kite', 'kitten', 'kiwi',
  'knee', 'kneel', 'knife', 'knight', 'knit', 'knob', 'knock', 'knot', 'know', 'koala',
  'krill', 'label', 'labor', 'lace', 'lack', 'ladder', 'ladle', 'lady', 'ladybug',
  'lagoon', 'lake', 'lamb', 'lame', 'lamp', 'land', 'lane', 'lantern', 'lap', 'laptop',
  'lard', 'lark', 'larva', 'laser', 'lash', 'lasso', 'last', 'latch', 'late', 'laugh',
  'lava', 'law', 'lawn', 'lawyer', 'lay', 'layer', 'lazy', 'lead', 'leaf', 'leak',
  'lean', 'leap', 'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'leek', 'left',
  'leg', 'legend', 'lego', 'lemonade', 'lemur', 'lend', 'length', 'lens', 'lentil',
  'leopard', 'lesson', 'letter', 'lettuce', 'level', 'lever', 'liar', 'liberty',
  'library', 'lick', 'lid', 'life', 'lift', 'light', 'lilac', 'lily', 'limb', 'lime',
  'limit', 'limp', 'line', 'linen', 'link', 'lion', 'lip', 'lipstick', 'liquid',
  'list', 'litter', 'live', 'lizard', 'llama', 'load', 'loaf', 'loan', 'lobster',
  'local', 'lock', 'locket', 'locust', 'lodge', 'log', 'logic', 'logo', 'lollipop',
  'lonely', 'long', 'look', 'loop', 'loose', 'lord', 'lorry', 'lose', 'lot', 'lotion',
  'lotus', 'loud', 'lounge', 'love', 'low', 'loyal', 'luck', 'luggage', 'lullaby',
  'lumber', 'lump', 'lunch', 'lung', 'lure', 'lush', 'lust', 'lute', 'luxury', 'lyric',
];

export const MEDIUM_WORDS = [
  'bicycle', 'castle', 'dinosaur', 'elephant', 'firefighter', 'guitar', 'helicopter',
  'internet', 'jungle', 'kangaroo', 'lighthouse', 'mountain', 'notebook', 'octopus',
  'piano', 'rainbow', 'sandwich', 'telescope', 'umbrella', 'volcano', 'waterfall',
  'xylophone', 'yacht', 'zebra', 'astronaut', 'butterfly', 'crocodile', 'dragon',
  'envelope', 'flashlight', 'giraffe', 'hamburger', 'igloo', 'jellyfish', 'knight',
  'laptop', 'mermaid', 'ninja', 'ostrich', 'penguin', 'quilt', 'robot', 'skeleton',
  'tornado', 'unicorn', 'vampire', 'wizard', 'yogurt', 'zombie', 'accordion', 'airport',
  'alarm', 'alien', 'almond', 'anchor', 'angel', 'antenna', 'apartment', 'apricot',
  'aquarium', 'armor', 'artist', 'asteroid', 'athlete', 'attic', 'avocado', 'badge',
  'bagel', 'bakery', 'balcony', 'balloon', 'banana', 'bandage', 'banjo', 'barbecue',
  'barber', 'barnacle', 'barrel', 'baseball', 'basement', 'basket', 'battery', 'beacon',
  'beaker', 'beanie', 'beaver', 'bedroom', 'beehive', 'beetle', 'beggar', 'bellhop',
  'bench', 'beret', 'bicycle', 'billboard', 'binoculars', 'biology', 'birch', 'birthmark',
  'biscuit', 'blackboard', 'blacksmith', 'blanket', 'blender', 'blimp', 'blizzard',
  'blockbuster', 'blueberry', 'blueprint', 'blush', 'boardwalk', 'bobcat', 'bodyguard',
  'boiler', 'bonfire', 'bookcase', 'bookstore', 'boomerang', 'boots', 'border', 'boulder',
  'bouquet', 'bowling', 'boxer', 'boyscout', 'bracelet', 'bracket', 'brainstorm', 'brake',
  'branch', 'brass', 'breadbox', 'breakfast', 'breath', 'brewery', 'bricklayer', 'briefcase',
  'broccoli', 'bronze', 'broomstick', 'brownie', 'brunch', 'bubblegum', 'bucket', 'buffalo',
  'buggy', 'builder', 'bulldozer', 'bumblebee', 'bungalow', 'bunker', 'burrito', 'busdriver',
  'butcher', 'butterfly', 'cabinet', 'cablecar', 'cactus', 'cafeteria', 'calculator',
  'calendar', 'calculator', 'camcorder', 'campfire', 'canary', 'candelabra', 'cannon',
  'canoe', 'canyon', 'cape', 'cappuccino', 'captain', 'caravan', 'cardboard', 'cardigan',
  'carnival', 'carousel', 'carpenter', 'carriage', 'carrotcake', 'cartoon', 'carwash',
  'cashier', 'cassette', 'cathedral', 'cauliflower', 'caviar', 'cayenne', 'ceiling',
  'celebrity', 'cellar', 'cello', 'cement', 'centaur', 'ceramic', 'cereal', 'chainsaw',
  'chalkboard', 'champagne', 'chandelier', 'chariot', 'checkers', 'cheddar', 'cheerleader',
  'cheesecake', 'chemist', 'cherrypie', 'chess', 'chestnut', 'chickenwing', 'chihuahua',
  'chimney', 'chinchilla', 'chipmunk', 'chiropractor', 'chocolate', 'choir', 'chopsticks',
  'christmas', 'cider', 'cigarette', 'cinnamon', 'circus', 'citadel', 'cityhall', 'clam',
  'clarinet', 'classroom', 'claypot', 'cleopatra', 'cliff', 'clipboard', 'cloak', 'clocktower',
  'closet', 'clothespin', 'clover', 'clownfish', 'coal', 'coaster', 'cobra', 'cockroach',
  'coconut', 'coffeebean', 'coffeemaker', 'coin', 'cola', 'coliseum', 'collar', 'colonel',
  'comet', 'compass', 'computer', 'concert', 'conductor', 'cone', 'confetti', 'congress',
  'console', 'constable', 'container', 'cookbook', 'cookie', 'copper', 'coral', 'cord',
  'corkscrew', 'cornfield', 'corridor', 'cosmetics', 'costume', 'cottage', 'cottoncandy',
  'couch', 'cougar', 'country', 'coupon', 'courtroom', 'cousin', 'cowboy', 'crabapple',
  'cracker', 'cranberry', 'crater', 'crayfish', 'creamcheese', 'creature', 'credit',
  'creek', 'crepe', 'crib', 'cricket', 'criminal', 'crisp', 'crocodile', 'croissant',
  'crossbow', 'crosswalk', 'crowbar', 'crown', 'cruise', 'crust', 'crystal', 'cucumber',
  'cupboard', 'cupcake', 'curtain', 'cushion', 'custard', 'cylinder', 'cymbal', 'daffodil',
  'dagger', 'daisy', 'dalmatian', 'dam', 'dancer', 'dandelion', 'dartboard', 'dashboard',
  'database', 'daydream', 'deadline', 'dealer', 'decade', 'december', 'decision', 'decor',
  'deer', 'defender', 'degree', 'deli', 'delivery', 'demon', 'dentist', 'deodorant',
  'desert', 'designer', 'desk', 'dessert', 'detective', 'detour', 'dewdrop', 'diagram',
  'diamond', 'diaper', 'dictionary', 'diesel', 'diet', 'dinghy', 'dinner', 'dinosaur',
  'diploma', 'director', 'dirtbike', 'disaster', 'disco', 'discount', 'dishwasher',
  'dispenser', 'diving', 'dock', 'doctor', 'document', 'dodgeball', 'doghouse', 'dollhouse',
  'dolphin', 'domino', 'donkey', 'donut', 'door', 'doorknob', 'doorstep', 'dormitory',
  'dragonfly', 'drain', 'drawbridge', 'drawer', 'dream', 'dresser', 'drill', 'drink',
  'driveway', 'drone', 'droplet', 'drum', 'drummer', 'dryer', 'duckling', 'duffel',
  'dumbbell', 'dumpling', 'dumpster', 'dune', 'dungeon', 'durian', 'duster', 'dwarf',
  'dynamite', 'eagle', 'earphone', 'earthquake', 'easel', 'easter', 'eclair', 'economy',
  'editor', 'eel', 'eggroll', 'egypt', 'elastic', 'elevator', 'elf', 'elk', 'email',
  'emerald', 'emperor', 'empire', 'engine', 'engineer', 'engraving', 'entrance', 'envelope',
  'eraser', 'escalator', 'espresso', 'estate', 'ethernet', 'europe', 'evidence', 'exam',
  'excavator', 'exercise', 'exhibit', 'exit', 'expert', 'explosion', 'extension', 'eyelash',
  'fabric', 'facepaint', 'factory', 'fairy', 'falcon', 'family', 'fan', 'farmhouse',
  'fashion', 'fastfood', 'father', 'faucet', 'fax', 'feather', 'feature', 'february',
  'federation', 'feedback', 'feeling', 'fence', 'ferris', 'ferry', 'festival', 'fever',
  'fiber', 'fiction', 'fiddle', 'field', 'fig', 'figure', 'file', 'filter', 'finch',
  'finger', 'finish', 'firealarm', 'fireplace', 'firetruck', 'firewood', 'firework',
  'firstaid', 'fishhook', 'fishing', 'fist', 'flag', 'flame', 'flamingo', 'flash',
  'flatiron', 'flavor', 'flea', 'fleece', 'flight', 'flint', 'flipflop', 'flood',
  'floor', 'florist', 'flour', 'flower', 'flu', 'flute', 'fly', 'flytrap', 'foam',
  'fog', 'folder', 'follow', 'font', 'food', 'football', 'footprint', 'forehead',
  'forest', 'forever', 'fork', 'formula', 'fortune', 'fossil', 'fountain', 'fox',
  'frame', 'freckle', 'freezer', 'french', 'fresco', 'friday', 'fridge', 'friend',
  'frisbee', 'fritz', 'frog', 'frontier', 'frosting', 'fruit', 'fry', 'fudge', 'fuel',
  'fungus', 'funnel', 'fur', 'furnace', 'furniture', 'futon', 'gadget', 'galaxy',
  'gallery', 'gallon', 'gamble', 'game', 'garage', 'garbage', 'garden', 'garlic',
  'garnish', 'gasoline', 'gate', 'gateway', 'gazebo', 'gear', 'gecko', 'gem', 'general',
  'generator', 'genie', 'genius', 'geometry', 'gerbil', 'germ', 'gesture', 'geyser',
  'ghost', 'giant', 'gift', 'giggle', 'gingerbread', 'giraffe', 'girdle', 'glacier',
  'gladiator', 'glasses', 'glider', 'globe', 'glove', 'glue', 'gnome', 'goal', 'goat',
  'goblet', 'goblin', 'gold', 'goldfish', 'golf', 'gondola', 'goose', 'gorilla',
  'gospel', 'gossip', 'gourd', 'government', 'graffiti', 'grain', 'gram', 'grandparent',
  'grape', 'grapefruit', 'graph', 'grass', 'grave', 'gravel', 'gravy', 'grease',
  'greenhouse', 'grenade', 'grid', 'grill', 'grin', 'grip', 'grocery', 'groom',
  'groundhog', 'group', 'grove', 'growl', 'grumpy', 'guard', 'guava', 'guest', 'guide',
  'guitarist', 'gulf', 'gumball', 'gummy', 'gun', 'gutter', 'gymnast', 'gyro', 'habitat',
  'hacker', 'hail', 'hairbrush', 'hairdryer', 'halfpipe', 'hallway', 'halo', 'hamster',
  'handcuff', 'handshake', 'hangar', 'hanger', 'happiness', 'harbor', 'harmonica',
  'harp', 'harvest', 'hatchet', 'haunted', 'hawk', 'haystack', 'hazelnut', 'headache',
  'headband', 'headlight', 'headphone', 'health', 'heart', 'heatwave', 'hedgehog',
  'helicopter', 'helmet', 'help', 'hermit', 'hero', 'hibiscus', 'hiccup', 'highchair',
  'highheel', 'highway', 'hike', 'hinge', 'hippo', 'history', 'hockey', 'holiday',
  'hollywood', 'hologram', 'home', 'honeycomb', 'hoodie', 'hook', 'hoop', 'horizon',
  'hornet', 'horse', 'hospital', 'hotair', 'hotdog', 'hotel', 'hourglass', 'house',
  'hoverboard', 'howl', 'hubcap', 'hula', 'hummingbird', 'hunter', 'hurricane', 'husband',
  'hut', 'hydrant', 'hyena', 'icecream', 'icicle', 'icon', 'idea', 'identity', 'igloo',
  'iguana', 'illness', 'image', 'impact', 'import', 'impulse', 'income', 'index',
  'industry', 'infant', 'infinite', 'injection', 'inkwell', 'inn', 'insect', 'inside',
  'instant', 'instrument', 'interest', 'internet', 'interview', 'invader', 'invention',
  'invitation', 'iris', 'iron', 'island', 'ivory', 'jackal', 'jacket', 'jackhammer',
  'jaguar', 'jail', 'jalapeno', 'january', 'jar', 'jasmine', 'jaw', 'jazz', 'jeep',
  'jelly', 'jersey', 'jet', 'jewelry', 'jigsaw', 'jingle', 'job', 'jockey', 'jogger',
  'journal', 'journey', 'judge', 'judo', 'juice', 'july', 'jumbo', 'jump', 'june',
  'jungle', 'junior', 'jupiter', 'justice', 'kangaroo', 'karaoke', 'karate', 'kayak',
  'kebab', 'keeper', 'ketchup', 'kettle', 'keyboard', 'keyhole', 'khaki', 'kick',
  'kidney', 'killer', 'kilo', 'kimono', 'king', 'kingdom', 'kiss', 'kitchen', 'kite',
  'kitten', 'kiwi', 'knee', 'knight', 'knit', 'knock', 'knot', 'koala', 'label',
  'laboratory', 'ladder', 'ladybug', 'lagoon', 'lake', 'lamb', 'lamp', 'landmark',
  'landscape', 'lantern', 'laptop', 'laser', 'lasso', 'latch', 'laugh', 'laundry',
  'lava', 'lawyer', 'layer', 'leader', 'leaf', 'league', 'leak', 'leap', 'leather',
  'lecture', 'leek', 'legend', 'lego', 'lemon', 'lemur', 'lens', 'leopard', 'lesson',
  'letter', 'lettuce', 'level', 'library', 'license', 'lick', 'lid', 'lifeboat',
  'lifeguard', 'lift', 'light', 'lighthouse', 'lightning', 'lilac', 'lily', 'limb',
  'lime', 'limousine', 'line', 'linen', 'link', 'lion', 'lipstick', 'liquid', 'lizard',
  'llama', 'lobster', 'lock', 'locomotive', 'lodge', 'log', 'logic', 'logo', 'lollipop',
  'london', 'lonely', 'loop', 'lottery', 'lounge', 'love', 'lowrider', 'loyalty',
  'luck', 'luggage', 'lumber', 'lunch', 'lung', 'lute', 'luxury', 'lyrics', 'macaroni',
  'machine', 'magazine', 'magic', 'magnet', 'magnifier', 'mailbox', 'makeup', 'mall',
  'mammoth', 'manager', 'mango', 'mansion', 'mantle', 'maple', 'marathon', 'marble',
  'march', 'margarine', 'marina', 'marker', 'market', 'marmalade', 'marriage', 'marsh',
  'marshmallow', 'mask', 'massage', 'master', 'match', 'material', 'math', 'matrix',
  'matter', 'mattress', 'may', 'mayor', 'maze', 'meadow', 'meal', 'measure', 'meatball',
  'mechanic', 'medal', 'medicine', 'meeting', 'melon', 'melody', 'member', 'memory',
  'menu', 'merchant', 'mercury', 'mermaid', 'message', 'metal', 'meteor', 'meter',
  'microphone', 'microscope', 'microwave', 'middle', 'midnight', 'military', 'milkshake',
  'mill', 'million', 'mime', 'mind', 'mine', 'mineral', 'minivan', 'mint', 'minute',
  'mirror', 'missile', 'mission', 'mist', 'mitten', 'mixer', 'moat', 'mobile', 'model',
  'modem', 'mohawk', 'moisture', 'molecule', 'mom', 'monarch', 'monday', 'money',
  'monitor', 'monkey', 'monster', 'month', 'monument', 'moon', 'moose', 'mop', 'morning',
  'morse', 'mortal', 'mosaic', 'mosquito', 'moss', 'motel', 'moth', 'mother', 'motion',
  'motor', 'motorcycle', 'mound', 'mountain', 'mouse', 'moustache', 'mouth', 'movie',
  'mower', 'mud', 'muffin', 'mug', 'mule', 'multiverse', 'museum', 'mushroom', 'music',
  'mustache', 'mustard', 'mystery', 'myth', 'nail', 'name', 'napkin', 'narrator',
  'nature', 'navy', 'necklace', 'nectar', 'needle', 'neighbor', 'neptune', 'nest',
  'network', 'news', 'newspaper', 'night', 'nightmare', 'ninja', 'nitrogen', 'noble',
  'noise', 'noodle', 'north', 'nose', 'note', 'notebook', 'notice', 'novel', 'november',
  'nuclear', 'nugget', 'number', 'nurse', 'nutmeg', 'oak', 'oar', 'oasis', 'oatmeal',
  'obelisk', 'object', 'obsidian', 'ocean', 'octagon', 'octopus', 'odor', 'office',
  'oil', 'olive', 'olympics', 'omelet', 'onion', 'opera', 'opinion', 'orange', 'orbit',
  'orchard', 'orchid', 'order', 'organ', 'origami', 'ostrich', 'otter', 'oven',
  'owl', 'owner', 'oxygen', 'oyster', 'pacifier', 'package', 'paddle', 'page', 'pagoda',
  'paint', 'painter', 'pajamas', 'palace', 'palm', 'pan', 'pancake', 'panda', 'panel',
  'panic', 'panther', 'pantry', 'pants', 'papaya', 'paper', 'parachute', 'parade',
  'paradise', 'parcel', 'parent', 'park', 'parking', 'parrot', 'parsley', 'partner',
  'party', 'passage', 'passenger', 'passport', 'pasta', 'pastry', 'patch', 'path',
  'patient', 'pattern', 'pause', 'pavement', 'paw', 'payment', 'pea', 'peace',
  'peach', 'peacock', 'peak', 'peanut', 'pear', 'pearl', 'pebble', 'pedal', 'pencil',
  'penguin', 'penny', 'people', 'pepper', 'perfume', 'period', 'permit', 'person',
  'pet', 'petal', 'phone', 'photo', 'piano', 'pickle', 'picture', 'pie', 'piece',
  'pig', 'pigeon', 'pile', 'pill', 'pillow', 'pilot', 'pin', 'pine', 'pineapple',
  'ping', 'pink', 'pioneer', 'pipe', 'pirate', 'pistol', 'pitch', 'pizza', 'place',
  'planet', 'plank', 'plant', 'plastic', 'plate', 'platform', 'play', 'player',
  'playground', 'plaza', 'pleasure', 'pliers', 'plot', 'plow', 'plug', 'plum',
  'plumber', 'plus', 'pocket', 'podcast', 'poem', 'poet', 'point', 'poison', 'poker',
  'polar', 'pole', 'police', 'polish', 'politics', 'pollen', 'polo', 'polygon',
  'pomegranate', 'pond', 'pony', 'pool', 'popcorn', 'pope', 'poppy', 'porch',
  'porcupine', 'portal', 'porter', 'portfolio', 'portrait', 'post', 'postage',
  'postcard', 'poster', 'pot', 'potato', 'potion', 'pottery', 'pouch', 'pound',
  'powder', 'power', 'practice', 'prairie', 'prayer', 'present', 'president',
  'press', 'pretzel', 'price', 'pride', 'priest', 'prime', 'prince', 'princess',
  'printer', 'prison', 'prize', 'problem', 'process', 'product', 'professor',
  'program', 'project', 'promise', 'proof', 'propeller', 'protein', 'protest',
  'proud', 'provider', 'prune', 'psychic', 'pub', 'public', 'pudding', 'puffin',
  'pump', 'pumpkin', 'punch', 'puppet', 'puppy', 'purple', 'purse', 'puzzle',
  'pyramid', 'python', 'quail', 'quality', 'quarter', 'quartz', 'queen', 'quest',
  'question', 'quiche', 'quill', 'quilt', 'quiz', 'quote', 'rabbit', 'raccoon',
  'race', 'racket', 'radar', 'radiator', 'radio', 'radish', 'raft', 'rage', 'rail',
  'railroad', 'rain', 'rainbow', 'raincoat', 'raisin', 'rake', 'rally', 'ram',
  'ramp', 'ranch', 'random', 'range', 'rank', 'rap', 'raspberry', 'rat', 'rate',
  'raven', 'razor', 'reach', 'reaction', 'read', 'ready', 'real', 'reason', 'rebel',
  'receipt', 'record', 'recorder', 'red', 'reef', 'referee', 'refuge', 'region',
  'register', 'regret', 'reindeer', 'relation', 'relay', 'relief', 'religion',
  'relish', 'remedy', 'remote', 'rent', 'repair', 'repeat', 'report', 'reptile',
  'rescue', 'research', 'reserve', 'resort', 'rest', 'restaurant', 'result',
  'retail', 'retire', 'return', 'reunion', 'review', 'revolution', 'reward',
  'rhino', 'rhythm', 'ribbon', 'rice', 'rich', 'ride', 'ridge', 'rifle', 'right',
  'ring', 'riot', 'ripple', 'rise', 'risk', 'river', 'road', 'roar', 'roast',
  'robe', 'robin', 'robot', 'rock', 'rocket', 'rodent', 'role', 'roll', 'roller',
  'romance', 'roof', 'room', 'rooster', 'root', 'rope', 'rose', 'rosemary', 'rotate',
  'rotten', 'rough', 'round', 'route', 'row', 'rowboat', 'royal', 'rubber', 'ruby',
  'rug', 'ruin', 'rule', 'ruler', 'rumor', 'run', 'runner', 'runway', 'rural',
  'rush', 'rust', 'rutabaga', 'sack', 'saddle', 'safari', 'safe', 'sail', 'sailor',
  'salad', 'salary', 'sale', 'salmon', 'salon', 'salt', 'salute', 'sample', 'sand',
  'sandbox', 'sandwich', 'santa', 'sap', 'sapphire', 'sardine', 'sash', 'satellite',
  'satin', 'sauce', 'sausage', 'savage', 'saw', 'saxophone', 'scale', 'scallop',
  'scar', 'scarecrow', 'scarf', 'scene', 'scent', 'schedule', 'school', 'science',
  'scissors', 'scooter', 'score', 'scorpion', 'scout', 'scramble', 'scrap', 'scream',
  'screen', 'screw', 'scribble', 'script', 'scroll', 'scuba', 'sculpture', 'sea',
  'seagull', 'seahorse', 'seal', 'search', 'season', 'seat', 'seaweed', 'second',
  'secret', 'section', 'secure', 'seed', 'seek', 'segment', 'select', 'selfie',
  'sell', 'semester', 'senator', 'senior', 'sense', 'sensor', 'sentence', 'series',
  'serpent', 'servant', 'server', 'session', 'set', 'seven', 'sew', 'shade',
  'shadow', 'shake', 'shampoo', 'shape', 'share', 'shark', 'sharp', 'shave',
  'shears', 'shed', 'sheep', 'sheet', 'shelf', 'shell', 'shelter', 'shepherd',
  'shield', 'shift', 'shine', 'ship', 'shirt', 'shock', 'shoe', 'shoot', 'shop',
  'shore', 'short', 'shot', 'shoulder', 'shout', 'show', 'shower', 'shrimp',
  'shrine', 'shrink', 'shrub', 'shuffle', 'shuttle', 'shy', 'sick', 'side',
  'sidewalk', 'siege', 'sight', 'sign', 'signal', 'signature', 'silence', 'silk',
  'silly', 'silver', 'simple', 'sin', 'singer', 'sink', 'sip', 'siren', 'sister',
  'site', 'situation', 'six', 'size', 'skate', 'skateboard', 'skeleton', 'sketch',
  'ski', 'skill', 'skin', 'skip', 'skirt', 'skull', 'sky', 'slam', 'slap', 'slave',
  'sled', 'sleep', 'sleeve', 'slice', 'slide', 'slime', 'sling', 'slip', 'slipper',
  'slope', 'slot', 'slow', 'slug', 'slum', 'smell', 'smile', 'smoke', 'smooth',
  'snack', 'snail', 'snake', 'snap', 'sneaker', 'sneeze', 'sniff', 'snore', 'snow',
  'snowball', 'snowboard', 'snowflake', 'snowman', 'soap', 'soccer', 'social',
  'sock', 'soda', 'sofa', 'soft', 'software', 'soil', 'solar', 'soldier', 'solid',
  'solo', 'solution', 'sombrero', 'son', 'song', 'sonnet', 'soot', 'soprano',
  'sorbet', 'sorrow', 'sort', 'soul', 'sound', 'soup', 'source', 'south', 'space',
  'spade', 'spaghetti', 'span', 'spare', 'spark', 'sparrow', 'spatula', 'speaker',
  'spear', 'special', 'speech', 'speed', 'spell', 'spend', 'sphere', 'spice',
  'spider', 'spike', 'spin', 'spinach', 'spine', 'spiral', 'spirit', 'spit',
  'splash', 'spleen', 'splinter', 'sponge', 'spoon', 'sport', 'spot', 'spotlight',
  'spray', 'spread', 'spring', 'sprinkle', 'sprint', 'sprout', 'spruce', 'spy',
  'square', 'squash', 'squid', 'squirrel', 'stable', 'stack', 'stadium', 'staff',
  'stage', 'stain', 'stair', 'stake', 'stall', 'stamp', 'stand', 'star', 'starch',
  'stare', 'start', 'state', 'station', 'statue', 'stay', 'steak', 'steam',
  'steel', 'steep', 'steer', 'stem', 'step', 'stereo', 'stew', 'stick', 'sticker',
  'still', 'sting', 'stir', 'stitch', 'stock', 'stomach', 'stone', 'stool',
  'stop', 'storage', 'store', 'storm', 'story', 'stove', 'strand', 'stranger',
  'strap', 'straw', 'strawberry', 'stream', 'street', 'strength', 'stress',
  'stretch', 'strike', 'string', 'strip', 'stripe', 'stroke', 'strong', 'structure',
  'struggle', 'student', 'studio', 'study', 'stuff', 'stump', 'stun', 'style',
  'subject', 'submarine', 'subway', 'success', 'sugar', 'suit', 'suitcase', 'sulfur',
  'summer', 'summit', 'sun', 'sunburn', 'sunday', 'sunflower', 'sunglasses',
  'sunlight', 'sunrise', 'sunset', 'sunshine', 'super', 'superhero', 'supply',
  'support', 'surf', 'surface', 'surfboard', 'surgeon', 'surname', 'surprise',
  'sushi', 'swallow', 'swamp', 'swan', 'swarm', 'sweater', 'sweep', 'sweet',
  'swim', 'swing', 'switch', 'sword', 'symbol', 'symphony', 'syrup', 'system',
  'table', 'tablet', 'taco', 'tadpole', 'tag', 'tail', 'tailor', 'tale', 'talent',
  'talk', 'tall', 'tambourine', 'tank', 'tap', 'tape', 'target', 'tarp', 'tart',
  'task', 'taste', 'tattoo', 'tavern', 'tax', 'taxi', 'tea', 'teacher', 'team',
  'tear', 'teaspoon', 'tech', 'technique', 'teen', 'teeth', 'telephone', 'telescope',
  'television', 'tell', 'temper', 'temple', 'tempo', 'ten', 'tenant', 'tennis',
  'tent', 'term', 'terminal', 'terrace', 'terrain', 'test', 'text', 'texture',
  'thanksgiving', 'theater', 'theme', 'theory', 'therapy', 'thermometer', 'think',
  'thorn', 'thought', 'thread', 'threat', 'throne', 'throw', 'thumb', 'thunder',
  'thursday', 'ticket', 'tide', 'tie', 'tiger', 'tile', 'till', 'time', 'timer',
  'tin', 'tinkle', 'tip', 'tire', 'tissue', 'title', 'toast', 'today', 'toe',
  'tofu', 'together', 'toilet', 'tomato', 'tomb', 'tone', 'tongue', 'tool',
  'tooth', 'toothbrush', 'top', 'topic', 'torch', 'tornado', 'torpedo', 'tortoise',
  'total', 'touch', 'tour', 'tourist', 'towel', 'tower', 'town', 'toy', 'track',
  'tractor', 'trade', 'traffic', 'trail', 'train', 'trait', 'tram', 'tramp',
  'transform', 'trap', 'trash', 'travel', 'tray', 'treasure', 'treat', 'tree',
  'trend', 'trial', 'triangle', 'tribe', 'trick', 'trip', 'trophy', 'tropical',
  'trouble', 'trout', 'truck', 'trumpet', 'trunk', 'trust', 'truth', 'try',
  'tub', 'tube', 'tuesday', 'tug', 'tulip', 'tuna', 'tunnel', 'turkey', 'turn',
  'turtle', 'tutor', 'tuxedo', 'twelve', 'twenty', 'twig', 'twilight', 'twin',
  'twist', 'type', 'typhoon', 'ukulele', 'umbrella', 'uncle', 'under', 'unicorn',
  'union', 'unit', 'universe', 'university', 'update', 'upgrade', 'upload',
  'upper', 'urban', 'urchin', 'urgent', 'urn', 'usage', 'use', 'user', 'usual',
  'vacation', 'vacuum', 'valley', 'value', 'van', 'vanilla', 'vapor', 'variety',
  'vase', 'vault', 'veal', 'vegan', 'veil', 'vein', 'velvet', 'vendor', 'venom',
  'vent', 'venue', 'verse', 'version', 'vest', 'vet', 'veteran', 'vibe', 'vice',
  'victim', 'victory', 'video', 'view', 'village', 'vine', 'vinegar', 'vineyard',
  'vintage', 'vinyl', 'violin', 'viper', 'virgin', 'virtual', 'virus', 'visa',
  'vision', 'visit', 'visor', 'vista', 'visual', 'vitamin', 'vivid', 'vocabulary',
  'voice', 'volcano', 'volleyball', 'volume', 'vote', 'vowel', 'voyage', 'vulture',
  'waffle', 'wagon', 'waist', 'wait', 'waiter', 'wake', 'walk', 'wall', 'wallet',
  'walnut', 'walrus', 'wand', 'war', 'wardrobe', 'warehouse', 'warm', 'warning',
  'warrior', 'wash', 'wasp', 'waste', 'watch', 'water', 'waterfall', 'watermelon',
  'wave', 'wax', 'way', 'wealth', 'weapon', 'wear', 'weather', 'web', 'wedding',
  'weed', 'week', 'weekend', 'weight', 'welcome', 'well', 'west', 'whale', 'wheat',
  'wheel', 'whip', 'whisk', 'whiskey', 'whisper', 'whistle', 'white', 'whole',
  'wick', 'widget', 'widow', 'width', 'wife', 'wifi', 'wig', 'wild', 'will',
  'willow', 'win', 'wind', 'windmill', 'window', 'wine', 'wing', 'wink', 'winner',
  'winter', 'wire', 'wisdom', 'wish', 'witch', 'witness', 'wizard', 'wolf',
  'woman', 'wonder', 'wood', 'wool', 'word', 'work', 'worker', 'world', 'worm',
  'worry', 'worship', 'worth', 'wound', 'wrap', 'wreath', 'wreck', 'wrench',
  'wrestle', 'wrinkle', 'wrist', 'write', 'writer', 'wrong', 'xray', 'yacht',
  'yard', 'yarn', 'yawn', 'year', 'yeast', 'yell', 'yellow', 'yoga', 'yogurt',
  'yolk', 'young', 'youth', 'zebra', 'zero', 'zigzag', 'zinc', 'zipper', 'zone',
  'zoo', 'zoom', 'zucchini',
];

export const HARD_WORDS = [
  'archaeology', 'bureaucracy', 'choreography', 'democracy', 'encyclopedia',
  'fluorescent', 'gymnastics', 'hippopotamus', 'improvisation', 'juxtaposition',
  'kaleidoscope', 'labyrinth', 'metamorphosis', 'narcissistic', 'onomatopoeia',
  'photosynthesis', 'quintessential', 'rhinoceros', 'sophisticated', 'tranquility',
  'unprecedented', 'ventriloquist', 'whimsical', 'xenophobia', 'zeppelin',
  'abbreviation', 'benevolent', 'circumference', 'discombobulated', 'exaggerate',
  'flabbergasted', 'grandiloquent', 'hallucination', 'idiosyncrasy', 'juggernaut',
  'magnanimous', 'nefarious', 'obfuscation', 'perspicacious', 'quizzical',
  'recalcitrant', 'serendipity', 'triskaidekaphobia', 'unscrupulous', 'vicissitude',
  'wanderlust', 'zeitgeist', 'aberration', 'acquiesce', 'adjudicate', 'allegory',
  'ambidextrous', 'anachronism', 'antidisestablishmentarianism', 'apocalypse',
  'arbitrary', 'archipelago', 'assassination', 'astrophysics', 'atrocity',
  'autobiography', 'baccalaureate', 'balderdash', 'belligerent', 'biodiversity',
  'blasphemy', 'bourgeoisie', 'cacophony', 'calligraphy', 'catastrophe',
  'circumnavigate', 'claustrophobia', 'collaboration', 'commemorate', 'conglomerate',
  'connoisseur', 'conscientious', 'constellation', 'contradiction', 'corroborate',
  'cryptocurrency', 'decommission', 'defenestration', 'deteriorate', 'dichotomy',
  'disproportionate', 'eccentricity', 'electromagnetic', 'entrepreneur', 'epidemiology',
  'equilibrium', 'excommunication', 'existentialism', 'extraterrestrial', 'fabrication',
  'fiduciary', 'floccinaucinihilipilification', 'formidable', 'gastrointestinal',
  'grandeur', 'hallucinogenic', 'hegemony', 'heterogeneous', 'hippopotomonstrosesquipedaliophobia',
  'homogeneous', 'humongous', 'hydrodynamic', 'hyperbole', 'idempotent', 'illumination',
  'immunization', 'impeachment', 'inconceivable', 'indispensable', 'infrastructure',
  'insurmountable', 'intellectual', 'intermittent', 'introspection', 'iridescent',
  'jurisprudence', 'kinesiology', 'kleptomaniac', 'lachrymose', 'lackadaisical',
  'machiavellian', 'malicious', 'manipulation', 'mathematician', 'melancholy',
  'meretricious', 'metamorphic', 'microorganism', 'misanthrope', 'mitochondria',
  'monochromatic', 'multifarious', 'nanotechnology', 'nomenclature', 'nonchalant',
  'obstreperous', 'oligarchy', 'omnipotent', 'ostentatious', 'overwhelming',
  'paradigm', 'paraphernalia', 'parliament', 'perpendicular', 'pharmaceutical',
  'phenomenon', 'philanthropy', 'phosphorescent', 'photosynthesis', 'pneumonia',
  'polyglot', 'precipitation', 'prestidigitation', 'procrastination', 'proletariat',
  'pseudonym', 'psychotherapy', 'pulchritudinous', 'quarantine', 'questionnaire',
  'rambunctious', 'reconnaissance', 'rehabilitation', 'rendezvous', 'responsibility',
  'revolutionary', 'ridiculous', 'sacrilegious', 'sarsaparilla', 'schizophrenia',
  'sensationalism', 'serendipitous', 'sesquipedalian', 'sibilance', 'simultaneous',
  'solicitation', 'sophistication', 'sphygmomanometer', 'spontaneous', 'steganography',
  'subterranean', 'supercilious', 'surreptitious', 'sustainability', 'sycophant',
  'synchronicity', 'telecommunication', 'temperamental', 'thermodynamics', 'totalitarian',
  'transcendental', 'ubiquitous', 'uncharacteristic', 'underestimate', 'unfortunately',
  'unimaginable', 'university', 'unnecessary', 'unorthodox', 'unprecedented',
  'valedictorian', 'ventriloquism', 'verisimilitude', 'vicissitudes', 'vulnerability',
  'wainscoting', 'wherewithal', 'xenogenesis', 'yesteryear', 'zoology',
  'absolution', 'acrimonious', 'adulation', 'affidavit', 'aggrandize', 'altruistic',
  'amalgamation', 'anathema', 'antediluvian', 'apotheosis', 'approbation', 'archaeologist',
  'ascertain', 'asperity', 'assiduous', 'atavistic', 'auspicious', 'avarice',
  'bellicose', 'bifurcation', 'bloviate', 'bombastic', 'bowdlerize', 'brobdingnagian',
  'bumptious', 'cabal', 'capricious', 'castigate', 'chicanery', 'churlish',
  'circumlocution', 'codswallop', 'compunction', 'concatenation', 'conflagration',
  'convivial', 'corpulent', 'coruscate', 'crepuscular', 'cupidity', 'deleterious',
  'demagogue', 'denouement', 'desultory', 'diaphanous', 'didactic', 'diffident',
  'dilatory', 'discomfit', 'dissemble', 'ebullient', 'effervescent', 'egregious',
  'eleemosynary', 'emollient', 'encomium', 'endemic', 'enervate', 'ephemeral',
  'equanimity', 'equivocate', 'erudite', 'esoteric', 'euphemism', 'evanescent',
  'execrable', 'exiguous', 'expeditious', 'extemporaneous', 'facetious', 'fallacious',
  'fastidious', 'fatuous', 'feckless', 'fecund', 'fervent', 'filibuster', 'finagle',
  'florid', 'fortuitous', 'fractious', 'friable', 'fulminate', 'garrulous',
  'gasconade', 'gauche', 'genuflect', 'germane', 'gesticulate', 'glib', 'grandiloquence',
  'gregarious', 'guttural', 'harangue', 'heuristic', 'hubris', 'iconoclast',
  'ignominious', 'imbroglio', 'impecunious', 'impetuous', 'inchoate', 'incorrigible',
  'indefatigable', 'indolent', 'ineffable', 'inexorable', 'ingenuous', 'inimical',
  'insouciant', 'intransigent', 'invective', 'inveterate', 'irascible', 'jejune',
  'jingoistic', 'laconic', 'lambent', 'languid', 'largesse', 'legerdemain',
  'libertine', 'licentious', 'liminal', 'loquacious', 'lugubrious', 'macabre',
  'mendacious', 'mercurial', 'minatory', 'miscreant', 'mordant', 'munificent',
  'nadir', 'nefarious', 'noisome', 'nonplussed', 'obdurate', 'obsequious',
  'oleaginous', 'onerous', 'opprobrium', 'ossify', 'ostensible', 'otiose',
  'parsimonious', 'peccadillo', 'pedantic', 'penurious', 'perfidious', 'perfunctory',
  'peripatetic', 'pernicious', 'persiflage', 'pertinacious', 'petulant', 'phlegmatic',
  'picayune', 'platitude', 'plethora', 'precocious', 'predilection', 'prevaricate',
  'probity', 'proclivity', 'prodigal', 'profligate', 'propitious', 'puerile',
  'pugnacious', 'pulchritude', 'punctilious', 'querulous', 'quotidian', 'raconteur',
  'rancor', 'rapacious', 'recidivist', 'recondite', 'redolent', 'refractory',
  'remonstrate', 'repugnant', 'reprobate', 'restive', 'risible', 'rubicund',
  'sagacious', 'salubrious', 'sanctimonious', 'sanguine', 'saturnine', 'schadenfreude',
  'scintillating', 'sedulous', 'sententious', 'sequacious', 'sibilant', 'sobriquet',
  'spendthrift', 'splenetic', 'stentorian', 'stolid', 'stratagem', 'stultify',
  'superfluous', 'supernumerary', 'surfeit', 'surreptitious', 'sycophantic',
  'taciturn', 'tautology', 'temerity', 'tendentious', 'timorous', 'trenchant',
  'truculent', 'turbid', 'umbrage', 'unctuous', 'uxorious', 'vacillate',
  'vainglorious', 'vapid', 'venal', 'verdant', 'vicarious', 'vindicate',
  'virago', 'vituperative', 'vociferous', 'voluble', 'wheedle', 'winsome',
  'xenial', 'yokel', 'zealous',
];
