/**
 * Roast-style prompts — {name} is replaced with target player's name
 */
const PROMPTS = [
  'What would {name} do first during a zombie apocalypse?',
  'What excuse does {name} use the most?',
  'What would {name} become famous for?',
  'What is {name} secretly terrible at?',
  'If {name} became rich, what would they waste money on?',
  'What would {name}\'s villain origin story be?',
  'What is {name}\'s most used Google search?',
  'What would {name} name their podcast?',
  'What does {name} do at 3 AM?',
  'What would {name}\'s dating app bio say?',
  'What is {name}\'s toxic trait (lovingly)?',
  'What would {name} get cancelled for?',
  'What would {name} do if they won the lottery and lost it in a week?',
  'What is {name}\'s go-to karaoke song?',
  'What would {name} be arrested for (jokingly)?',
  'What would {name}\'s reality TV show be called?',
  'What is {name}\'s most chaotic purchase?',
  'What would {name} do on a first date disaster?',
  'What would {name}\'s LinkedIn headline be?',
  'What is {name}\'s superpower in friend group?',
  'What would {name} yell in a haunted house?',
  'What would {name} bring to a deserted island (useless edition)?',
  'What is {name}\'s Roman Empire (thing they think about constantly)?',
  'What would {name}\'s TED Talk be about?',
  'What would {name} do if they were invisible for a day?',
  'What is {name}\'s most unhinged food order?',
  'What would {name}\'s WiFi password be?',
  'What would {name} do if their phone died at a party?',
  'What is {name}\'s biggest "it\'s not that deep" moment?',
  'What would {name} name their pet rock?',
  'What would {name} do during a group project?',
  'What is {name}\'s red flag that\'s also a green flag?',
  'What would {name}\'s autobiography chapter 1 be titled?',
  'What would {name} do if they met their celebrity crush?',
  'What is {name}\'s most dramatic overreaction?',
  'What would {name} post if they had no filter?',
  'What would {name} do at a wedding they weren\'t invited to?',
  'What is {name}\'s secret hobby nobody knows about?',
  'What would {name}\'s last words be (in a funny movie)?',
  'What would {name} do if they were CEO for one day?',
  'What is {name}\'s most iconic catchphrase?',
  'What would {name} do if they saw a ghost?',
  'What would {name}\'s Amazon order history reveal?',
  'What is {name}\'s biggest "trust me bro" moment?',
  'What would {name} do at a silent retreat?',
  'What would {name}\'s spirit animal be?',
  'What is {name}\'s most controversial hot take?',
  'What would {name} do if they were late to their own wedding?',
  'What would {name}\'s villain laugh sound like?',
  'What is {name}\'s go-to excuse for being late?',
  'What would {name} do if they found out they\'re in a simulation?',
  'What would {name}\'s theme song be?',
  'What is {name}\'s most embarrassing childhood memory (make one up)?',
  'What would {name} do if they had to survive on only one food forever?',
  'What would {name}\'s mugshot caption be?',
  'What is {name}\'s biggest "main character" moment?',
  'What would {name} do if they became a meme?',
  'What would {name}\'s horoscope say today?',
  'What is {name}\'s most chaotic group chat contribution?',
  'What would {name} do if they lost a bet and had to shave their head?',
  'What would {name}\'s Nobel Prize be for?',
  'What is {name}\'s most used emoji?',
  'What would {name} do at a karaoke bar after one drink?',
  'What would {name}\'s OnlyFans bio be (PG-13 joke)?',
  'What is {name}\'s biggest "I can explain" moment?',
  'What would {name} do if they were stuck in an elevator?',
  'What would {name}\'s Yelp review of life be?',
  'What is {name}\'s most dramatic breakup line?',
  'What would {name} do if they had to teach a kindergarten class?',
  'What would {name}\'s FBI file say?',
  'What is {name}\'s biggest flex that\'s actually embarrassing?',
  'What would {name} do if they won a free vacation to their least favorite place?',
  'What would {name}\'s stand-up comedy opener be?',
  'What is {name}\'s most chaotic New Year\'s resolution?',
  'What would {name} do if they accidentally liked their ex\'s photo from 2019?',
  'What would {name}\'s gaming username be?',
  'What is {name}\'s biggest "hold my beer" moment?',
  'What would {name} do if they were a contestant on Survivor?',
  'What would {name}\'s fortune cookie say?',
  'What is {name}\'s most unhinged DoorDash order note?',
  'What would {name} do if they had to give a speech with no preparation?',
  'What would {name}\'s Wikipedia "early life" section say?',
  'What is {name}\'s biggest "that\'s so me" moment?',
  'What would {name} do if they found $20 on the ground?',
  'What would {name}\'s villain monologue be?',
  'What is {name}\'s most iconic fail?',
  'What would {name} do if they were president for 5 minutes?',
  'What would {name}\'s alarm clock label say?',
  'What is {name}\'s biggest "no thoughts head empty" moment?',
  'What would {name} do at a buffet?',
  'What would {name}\'s drag name be?',
  'What is {name}\'s most chaotic Uber ride story?',
  'What would {name} do if they had to fight one duck-sized horse?',
  'What would {name}\'s gravestone quote be (funny)?',
  'What is {name}\'s biggest "I\'m built different" moment?',
  'What would {name} do if they were on a reality dating show?',
  'What would {name}\'s AI-generated portrait look like?',
  'What is {name}\'s most dramatic "I\'m fine" moment?',
  'What would {name} do if they had unlimited Uber Eats for a day?',
  'What would {name}\'s villain outfit be?',
  'What is {name}\'s biggest "plot twist" energy?',
  'What would {name} do if they were the last person awake at a sleepover?',
  'What would {name}\'s criminal mastermind plan be?',
  'What is {name}\'s most iconic drunk text?',
  'What would {name} do if they had to live in a sitcom?',
  'What would {name}\'s superhero name be (terrible)?',
  'What is {name}\'s biggest "trust the process" fail?',
  'What would {name} do if they saw their doppelgänger?',
  'What would {name}\'s Yelp review of their own personality be?',
  'What is {name}\'s most chaotic vacation story?',
  'What would {name} do if they had to survive a week without WiFi?',
  'What would {name}\'s LinkedIn recommendation from a friend say?',
  'What is {name}\'s biggest "it\'s giving..." energy?',
  'What would {name} do if they were a contestant on Wheel of Fortune?',
  'What would {name}\'s evil twin be like?',
  'What is {name}\'s most unhinged group costume idea?',
  'What would {name} do if they had to babysit 10 kids?',
  'What would {name}\'s most viral TikTok be about?',
  'What is {name}\'s biggest "I\'m not like other girls/guys" moment?',
  'What would {name} do if they were stuck in traffic for 8 hours?',
  'What would {name}\'s award acceptance speech be?',
  'What is {name}\'s most chaotic "I\'ll be there in 5 minutes"?',
  'What would {name} do if they had to eat something they hate for $1000?',
  'What would {name}\'s theme park ride be called?',
  'What is {name}\'s biggest "down bad" moment?',
  'What would {name} do if they were a ghost haunting their friends?',
  'What would {name}\'s most controversial pizza topping choice be?',
  'What is {name}\'s most iconic "bruh" moment?',
  'What would {name} do if they had to give relationship advice?',
  'What would {name}\'s villain lair look like?',
  'What is {name}\'s biggest "I told you so" moment?',
  'What would {name} do if they won a lifetime supply of something useless?',
  'What would {name}\'s most chaotic Amazon review be?',
  'What is {name}\'s most dramatic "I\'m leaving" (but never leaves) moment?',
  'What would {name} do if they were a contestant on Family Feud?',
  'What would {name}\'s most iconic Halloween costume be?',
  'What is {name}\'s biggest "no cap" lie?',
  'What would {name} do if they had to survive a horror movie?',
  'What would {name}\'s most unhinged group chat name suggestion be?',
  'What is {name}\'s most chaotic "let\'s get food" decision?',
  'What would {name} do if they were a weather reporter during a storm?',
  'What would {name}\'s most iconic "that\'s what she said" setup be?',
  'What is {name}\'s biggest "I\'m the main character" delusion?',
  'What would {name} do if they had to host a game show?',
  'What would {name}\'s most dramatic plot twist be?',
  'What is {name}\'s most iconic "wait what" moment?',
];

const usedByRoom = new Map();

export function getRandomPrompt(roomCode, targetName) {
  if (!usedByRoom.has(roomCode)) usedByRoom.set(roomCode, new Set());
  const used = usedByRoom.get(roomCode);
  let available = PROMPTS.filter((_, i) => !used.has(i));
  if (available.length === 0) {
    used.clear();
    available = PROMPTS;
  }
  const idx = PROMPTS.indexOf(available[Math.floor(Math.random() * available.length)]);
  used.add(idx);
  return PROMPTS[idx].replace(/\{name\}/g, targetName);
}

export function clearPromptHistory(roomCode) {
  usedByRoom.delete(roomCode);
}

export function getPromptCount() {
  return PROMPTS.length;
}
